#!/bin/bash
##############################################################################
# Copyright (c) 2015 Jonas Bjurel and others.
# sfb@consultron.com
# jonasbjurel@hotmail.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
umask 0002
PWFILE=$HOME/.cipassword
cat $PWFILE | /usr/bin/sudo -S $@
