#!/usr/bin/expect -f
##############################################################################
# Copyright (c) 2015 Jonas Bjurel and others.
# jonasbjurel@hotmail.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

##############################################################################
# Description:
# This script pulls the openrc credential file from the openStack controllers
# via the fuel master
#
# Usage:
# ./pull-cred <Fuel_IP> <Fuel_PASSWD> <ControllerNode_FQDN>
# example: 
# ./pull-cred 10.20.0.2 r00tme node-1.domain.tld
##############################################################################


set fuel_ip [lindex $argv 0]
set fuel_pass [lindex $argv 1]
set ctrl_fqdn [lindex $argv 2]

spawn ssh-keygen -f $::env(HOME)/.ssh/known_hosts -R $fuel_ip
expect "*hosts.old "
spawn ssh root@$fuel_ip
expect {
   -re ".*es.*o.*" {
   exp_send "yes\r"
   exp_continue
  }
  -re ".*sword.*" {
    exp_send "$fuel_pass\r"
  }
}

expect "# "

send "scp root@\$(IFS=\"|\" && Array=(\$(fuel node list | grep controller | head -n 1)) && echo \${Array\[4\]} | sed 's/^ *//g' | sed 's/\[ \t\]*$//'):openrc .\r"


expect "# "
send "exit\r"
expect "Connection to $fuel_ip closed. "

spawn scp root@$fuel_ip:openrc .
expect {
   -re ".*es.*o.*" {
   exp_send "yes\r"
   exp_continue
  }
  -re ".*sword.*" {
    exp_send "$fuel_pass\r"
  }
}
interact